FROM php:7.3-fpm-alpine3.9
MAINTAINER Marta Kicza <marta.agata.kicza@gmail.com>

RUN apk add --no-cache icu curl zlib libzip libpng libjpeg freetype \
  && apk add --no-cache --virtual devs icu-dev zlib-dev libzip-dev autoconf g++ make pcre-dev freetype-dev libjpeg-turbo-dev libmcrypt-dev libpng-dev \
  && apk add --no-cache xvfb\
  && docker-php-source extract \
  && pecl install apcu \
  && docker-php-ext-enable apcu \
  && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
  && docker-php-ext-install intl zip pdo opcache gd pdo_mysql \
  && docker-php-source delete \
  && apk del devs \
  && rm -f /usr/local/src/* \
  && php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
  && php composer-setup.php --install-dir=/usr/local/bin \
  && php -r "unlink('composer-setup.php');" \
  && rm -rf /usr/src/*

ADD . /var/www/

RUN cd /var/www \
  && composer.phar install --optimize-autoloader --apcu-autoloader \
  && composer.phar clear-cache 

WORKDIR /var/www
